import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '../styles/globals.css'
import Navbar from '@/components/Navbar'


const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="flex flex-col">
          <Navbar />
          <main className='bg-drop-bg ml-[100px] min-h-screen py-6 px-10'>{children}</main>
        </div>
      </body>  
    </html>
  )
}
